"""add priority to task

Revision ID: 2332b41677c3
Revises: cee73ed70011
Create Date: 2026-01-08 11:54:33.361708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2332b41677c3'
down_revision: Union[str, Sequence[str], None] = 'cee73ed70011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='medium'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'priority')
    # ### end Alembic commands ###
