"""Initial migration

Revision ID: cee73ed70011
Revises: 
Create Date: 2026-01-07 11:51:08.957158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cee73ed70011'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # This is an initial migration, and tables are assumed to exist due to previous create_all()
    # We will simply mark this revision as applied.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # For initial migration, downgrading would mean removing all tables.
    # We will simply mark this revision as reverted.
    pass
    # ### end Alembic commands ###