apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "todo.backend.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.port }}
    protocol: TCP