apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo.labels" . | nindent 4 }}
data:
  BACKEND_URL: "{{ .Values.config.backendUrl }}"