apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.databaseUrl }}
  GEMINI_API_KEYS: {{ .Values.secrets.geminiApiKeys }}
  BETTER_AUTH_SECRET: {{ .Values.secrets.betterAuthSecret }}